Goals_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
    resources :goals, only: [:index]
  end 

  resources :goals, except: :index 
  
  resource :session 
end

Goals_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Goals_App/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint(8)        not null, primary key
#  body       :text             not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ApplicationRecord
  belongs_to :user,
    foreign_key: :user_id,
    class_name: :User
end

Goals_App/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
require 'bcrypt'
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true 
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  attr_reader :password
  
  has_many :goals,
    foreign_key: :user_id,
    class_name: :Goal

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      return user 
    end 

    nil 
  end 

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token 
    self.session_token ||= generate_session_token
  end 

end

Goals_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user 

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user 
    @current_user ||= User.find_by(session_token: session[:session_token])
  end 

  def logged_in?
    !!(current_user)
  end 

  def require_logout
    redirect_to users_url if logged_in?
  end

  def logout
    session[:session_token] = nil 

    if current_user
      current_user.reset_session_token!
    else 
      @current_user = nil 
    end 
  end 
end

Goals_App/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new 
    @goal = Goal.new 
    render :new 
  end
  
  def create 
    @goal = Goal.new(goal_params)
  end 

  private 

  def goal_params 
    params.require(:goal).permit(:body, :user_id, :private?)
  end 
end

Goals_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logout, only: [:new, :create]

  def new 
    render :new 
  end 

  def show 
    redirect_to new_session_url
  end 

  def create 
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user 
      log_in_user!(@user)
      redirect_to user_url(@user)
    else 
      flash.now[:errors] = ["INVALID CREDENTIALS"]
      render :new 
    end 
  end 

  def destroy 
    logout
    redirect_to new_session_url 
  end 
end

Goals_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all 
    render :index 
  end 

  def show
    @user = User.find(params[:id])

    if @user 
      render :show 
    else  
      render json: "no user found", status: 404
    end 
  end 

  def new
    @user = User.new 
    render :new
  end 

  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new 
    end 
  end
  
  private 

  def user_params 
    params.require(:user).permit(:username, :password)
  end 
end

Goals_App/app/helpers/application_helper.rb
module ApplicationHelper
end

Goals_App/app/helpers/goals_helper.rb
module GoalsHelper
end

Goals_App/app/helpers/sessions_helper.rb
module SessionsHelper
end

Goals_App/app/helpers/users_helper.rb
module UsersHelper
end

Goals_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">

  <input type="submit" value="Logout :(">
</form>
  <head>
    <title>GoalsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

Goals_App/app/views/users/index.html.erb
<h1>Welcome! Here are all the goals:</h1>

Goals_App/app/views/users/new.html.erb
<h1>Sign up!</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=  form_authenticity_token %>">

  <label for="username">Username</label>
  <input id="username" type="text" name="user[username]" value="<%= @user.username %>">


  <label for="password">Password</label>
  <input id="password" type="text" name="user[password]" value="<%= @user.password %>">

  <input type="submit" value="Sign up!">
</form>

Goals_App/app/views/users/show.html.erb
<h1> Hello <%= @user.username %> </h1>